config/routes.rb
Rails.application.routes.draw do

  root 'cats#index'

  resources :cats

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validate :caption_is_present, if: -> { active? }
  validate :active, if: -> { featured? }

  before_save :update_featured_date, if: -> { featured? }
  before_save :activate, if: -> { featured? }

  def caption_is_present
    unless caption.present?
      errors[:caption] = 'a caption must be supplied'
    end
  end

  private

  def update_featured_date
    self.featured_on = Time.zone.now
  end

  def activate
    self.active = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :find_cat, except: [ :index, :new, :create ]
  respond_to :html, :json, only: [:index, :show]

  def index
    @cats = Cat.order :created_at
    respond_with @cats
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new cat_params

    if @cat.save
      redirect_to @cat, success: "meow"
    else
      flash[:error] = @cat.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    @cat.attributes = cat_params

    result = {}
    if @cat.save
      result = {redirect: (next_action == 'index' ? cats_path : edit_cat_path(@cat)), success: "meow"}
    else
      flash[:error] = @cat.errors.full_messages.to_sentence
      result = {render: :edit}
    end

    respond_to do |format|
      format.json do
        flash[:error] = result[:error] if result[:error].present? and result[:redirect].present?
        render json: result.merge(flash).merge(cat: @cat)
      end
      format.html do
        if result.keys.include? :redirect
          redirect_to result[:redirect], success: result[:success]
        else
          render result[:render]
        end
      end
    end
  end

  def destroy
    if @cat.destroy
      respond_to do |format|
        format.json do
          render json: {cats: Cat.order(:created_at), success: "Raour"}
        end
        format.html do
          redirect_to cats_path, success: "Raour"
        end
      end
    else
      redirect_to show_path, error: @cat.errors.full_messages.to_sentence
    end
  end

  private

  def find_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(
      :url,
      :caption,
      :active,
      :featured
    )
  end

  def next_action
    params[:next_action]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat, html: { class: "uk-form uk-form-stacked" } do |f| %>
  <div class="uk-form-row">
    <%= f.label :url, class: 'uk-form-label' %>
    <div class="uk-form-controls">
      <%= f.text_field :url, class: 'uk-form-width-large' %>
    </div>
  </div>
  <div class="uk-form-row">
    <%= f.label :caption, class: 'uk-form-label' %>
    <div class="uk-form-controls">
      <%= f.text_field :caption, class: 'uk-form-width-large' %>
    </div>
  </div>

  <div class="uk-form-row">
    <button type="submit" class="uk-button uk-button-primary">Save</button>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h2>Edit Cat</h2>

<%= react_component('Toolbar', {cat: @cat}) %>

<br />

<%= render 'form' %>

<%= react_component('GraphDemo') %>

app/views/cats/index.html.erb
<%= link_to "Moar Cat!", new_cat_path, class: 'uk-button uk-button-primary uk-float-right' %>

<h2>All Teh Cats!</h2>

<%= react_component('CatTable', {cats: @cats}) %>

app/views/cats/new.html.erb
<h2>You're a Kitty!</h2>

<%= render 'form' %>

app/views/cats/show.html.erb
<h2><%= @cat.caption %></h2>

<%= image_tag @cat.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatErWallADemoRepo</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>

<div class="uk-container">
  <h1><%= link_to 'Catz!!1!', root_path %></h1>
  <hr>
  <%- flash.each do |name, message| %>
    <div class="flash <%= name %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>

  <%= javascript_include_tag 'application' %>
</body>
</html>